description: This playbook sends email alerts to admins for Armorblox incidents that
  need review.
id: Armorblox Needs Review
inputs:
- description: "Receiver's mailing address."
  key: recipient_mail_address
  playbookInputQuery:
  required: true
  value:
    simple: xyz@gmail.com
name: Armorblox Needs Review
outputs:
- contextPath: Armorblox.Threat.remediation_actions
  description: Remediation Action for the incident under inspection.
  type: string
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 75f9948a-4330-4c25-86eb-2b4263af8761
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 75f9948a-4330-4c25-86eb-2b4263af8761
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${incident.armorbloxincidentid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Armorblox
      description: 'Check the recommended remediation action for any incident '
      id: 8c3d5112-83da-4163-85d7-d1b719441c02
      iscommand: true
      name: Get Remediation Action
      script: Armorblox|||armorblox-check-remediation-action
      type: regular
      version: -1
    taskid: 8c3d5112-83da-4163-85d7-d1b719441c02
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 190
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      htmlBody:
        simple: <html><body>Hello, <br><p>Armorblox Incident Id - <b>${incident.armorbloxincidentid}</b>
          Needs Review</p>Thank you.</body></html>
      subject:
        simple: NEEDS REVIEW
      to:
        simple: ${inputs.recipient_mail_address}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Mail Sender (New)
      description: Send an email
      id: 1501c195-fc64-4e86-88db-cfd478bb631f
      iscommand: true
      name: Send Email
      script: Mail Sender (New)|||send-mail
      type: regular
      version: -1
    taskid: 1501c195-fc64-4e86-88db-cfd478bb631f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 710
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Armorblox.Threat.remediation_actions
          operator: isEqualString
          right:
            value:
              simple: NEEDS REVIEW
      label: "YES"
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "YES":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      description: ""
      brand: ""
      id: fbcab54a-3258-4bcb-88f5-c3009593119f
      iscommand: false
      name: Is Review Needed?
      type: condition
      version: -1
    taskid: fbcab54a-3258-4bcb-88f5-c3009593119f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 360
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Review Not Needed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 936feb4c-4726-472c-87e3-4e6bc341d1d8
      iscommand: false
      name: Done
      script: Print
      type: regular
      version: -1
    taskid: 936feb4c-4726-472c-87e3-4e6bc341d1d8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -240,
          "y": 530
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Mail Sent successfully to ${inputs.recipient_mail_address}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: a1111d6d-6e09-4a04-89cd-65a1030040c4
      iscommand: false
      name: Mail Sent Successful
      script: Print
      type: regular
      version: -1
    taskid: a1111d6d-6e09-4a04-89cd-65a1030040c4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 890
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "7"
      "yes":
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Mail Sender (New)
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 2f97dd0b-f541-471d-87a8-3a6951c1e506
      iscommand: false
      name: Is Mail Sender Integration Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 2f97dd0b-f541-471d-87a8-3a6951c1e506
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 420,
          "y": 530
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Please configure Mail Sender (New) Integration to enable this feature
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 7ec451fa-cf14-44a8-89d3-8097f63de061
      iscommand: false
      name: Error Sending Mail
      script: Print
      type: regular
      version: -1
    taskid: 7ec451fa-cf14-44a8-89d3-8097f63de061
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 710
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 935,
        "width": 1330,
        "x": -240,
        "y": 50
      }
    }
  }
fromversion: 6.0.0
tests:
- No tests (auto formatted)
